### ISSUE TITLE
AirDrop stopped working

### ISSUE THREAD

**Issue by ArmandAgopian** [dosdude1/macos-catalina-patcher#10]
Hi, I updated my MacMini 5,1 (Mid-2011) to Catalina with the updater tool. Everything seems to be working except airdrop and sidecar. For some reason, they’re missing. I can search for airdrop in spotlight, but I get a “can’t be found” error. Airdrop used to work fine before, how can I fix it?

**Comment by ach881** [comment]
Same issue on MacBook Pro 8,1. In Finder preferences, there is no option for AirDrop in the Sidebar tab. 

When searching in finder, it returns the AirDrop application file (in Macintosh HD>System>Library>Core Services>Finder>Contents>Applications>AirDrop), but like @AGithub457 said, when I try to open the app I get the error message, "The operation can’t be completed because the item can’t be found."

Anyone know if there's a way to DL the AirDrop application from somewhere else?

**Comment by SanGuayaba** [comment]
Same problem here!

**Comment by sasuke4uchiwa** [comment]
same here airdrop not showing up in finder and cannot be opened but sidecar is working fine 

and i did a clean ssd instal on macbook pro mid 2009 5,3

**Comment by mdacunha90** [comment]
Same problem for me, MacBookPro8,1.

**Comment by janapos** [comment]
Same problem here, IMac 9,1. Anyone has an answer?

**Comment by AGithub457** [comment]
UPDATE: So here is what my research led to. Us with pre-2012 macs had a form of Airdrop support with the bonjour service. That is what we used to see, but it only worked with other macs. 2012-onwards, Apple completely changed the implementation of airdrop to use BT/WiFi-direct. Since we never needed to update past High Sierra, we never saw a change. Now that we are on Catalina, we technically do not have that new airdrop support (which also comes with handoff and continuity), which is why airdrop looked blank and said it couldn't be found.

Luckily there is a fix in form of a patch. [Continuity Activation Tool](https://github.com/dokterdok/Continuity-Activation-Tool/tree/beta) is a tool that manually changes some kexts to enable airdrop+features to supported hardware. In my case, I didn't need any hardware modifications, but your mileage may vary. Check his [compatibility guide](https://github.com/dokterdok/Continuity-Activation-Tool/wiki/Compatibility).

BEFORE YOU CLICK: Note, this is only officially supported up to Sierra. [Use this link to an issue on their repo to get it working properly on catalina](https://github.com/dokterdok/Continuity-Activation-Tool/issues/463#issuecomment-555374727), specifically the comment posted here

**Comment by janapos** [comment]
appreciate that so much! a bit late today I'll try to aplay de "Continuity Activation Tool" and report here the results.

**Comment by janapos** [comment]
I'm on catalina Patcher by @dosdude1

**Comment by janapos** [comment]
Unfortunately, Imac 9,1 needs an Apple Broadcom BCM94360CD+adapter. I'm so sorry but Airdrop is not such as an essential tool to pay for it more than $150. Thanks a lot indeed for the info

**Comment by yourcharlie23** [comment]
No Airdrop for me iMac11,2 (21.5-inch Mid 2010)
<"Mac-F2238AC8">
Card Type: AirPort Extreme  (0x168C, 0x8F)
"IOName" = "pci168c,2a"

I wish there will be a fix for this like the earlier broadcom card.

**Comment by SanGuayaba** [comment]
> No Airdrop for me iMac11,2 (21.5-inch Mid 2010)
> <"Mac-F2238AC8">
> Card Type: AirPort Extreme (0x168C, 0x8F)
> "IOName" = "pci168c,2a"
> 
> It is an Atheros card.
> I wish there will be a fix for this like the earlier broadcom card.

In fact, it's possible. I installed a bluetooth card that it was the macbook por mid 2012 bluetooth card, and it works perfect for me.

**Comment by yourcharlie23** [comment]
> > No Airdrop for me iMac11,2 (21.5-inch Mid 2010)
> > <"Mac-F2238AC8">
> > Card Type: AirPort Extreme (0x168C, 0x8F)
> > "IOName" = "pci168c,2a"
> > It is an Atheros card.
> > I wish there will be a fix for this like the earlier broadcom card.
> 
> In fact, it's possible. I installed a bluetooth card that it was the macbook por mid 2012 bluetooth card, and it works perfect for me.

Im not really sure if I need to replace both the wifi card and the bluetooth card as Airdrop uses both technologies. I have the Atheros wifi card and I have the bluetooth 2.+ ... I've read, you need a Broadcom wifi card and a bluetooth 4.+ but it is not guaranteed to work. 

Just wondering why iMac Mid 2010 is very special. In fact the older Macs from 2008 have AirDrop patch while the newer one has none. Maybe because they are focusing on the broadcom cards.

**Comment by AsedaDeveloper** [comment]
Same problem for me on my MacBook Pro 5,5
