### ISSUE TITLE
After Restart from Bootable Installer, Grey Screen with Stop Sign appears

### ISSUE THREAD

**Issue by Noselip** [dosdude1/macos-catalina-patcher#17]
Hello,

First of all thank you for creating this!
I ran into a problem trying to run the catalina patcher on my late 2008 macbook pro 5.1:
I created the bootable installer as explained in the video, then restarted the laptop, option key during restart, choose "EFI Boot" with the Catalina logo, apple logo with the waiting bar appears, then after two minutes a grey screen with a grey stop sign appears. It's not really a stop sign, but more of a circle with a crossed by a diagonal line.
Has anyone seen this behavior?

All the best,
Gregor

**Comment by Poodlemastah** [comment]
I get the same issue on my macbook 7,1 mid 2010 heres a sysinfo report;

[MacBook Mid2010 7,1 sysreport.zip](https://github.com/dosdude1/macos-catalina-patcher/files/4058723/MacBook.Mid2010.7.1.sysreport.zip)

**Comment by Noselip** [comment]
And here is my system report

![MacBook Pro Late2008, 5_1 sysreport](https://user-images.githubusercontent.com/59847588/72452813-75546300-37be-11ea-9a4b-7a75e02e8894.png)

**Comment by Arthey91** [comment]
Sometimes I get the same issue, when I start my Mac  _(MacBookPro8.1, early 2011)_.
Startup screen looks like: 

![prohibitory-icon](https://user-images.githubusercontent.com/46996130/72749902-9ac8de80-3bbb-11ea-8c14-e658bd1554a8.png)

For the moment I can reset my NVRAM / PRAM with pressing `alt` + `cmd` + `r` + `p` when restarting.
Found here: [https://support.apple.com/en-us/HT204063](https://support.apple.com/en-us/HT204063)

After that my Mac starts without any issues, but a few days later the problem is back there.

A solution would be awesome.

By the way, big thanks to @dosdude1 for this fantastic patcher! Now I can continue developing Apps for the current iOS version. :muscle::nerd_face:

**Comment by Japanat** [comment]
Same here, MB5,1 late 2008, installed latest patcher, downloaded latest Catalina version as for today and same stop sign at boot.
Tried cleaning nram, smc, to no avail.

**Comment by dosdude1** [comment]
This almost always happens due to an oddity with the USB drive being used. Using a different one will more than likely fix this issue.

**Comment by Japanat** [comment]
How can we be sure? Is that a way to check the pendrive? I'm going to try another pendrive but the one I used didn't had any issue whatsoever until now (and I bet it would show that's still good if I try like a scandisk or something similar under windows or on self booting software)...

**Comment by Japanat** [comment]
You were right, I used another pendrive and it worked! Many thanks!

**Comment by Noselip** [comment]
I bought a new pendrive now and got a step further! Could run the installation, however when the laptop restarts and the installation continues, after 10min I get this screen:
![942BB369-0CFE-4763-817F-181C1CC3F9F3](https://user-images.githubusercontent.com/59847588/74565983-b6cd5f00-4f72-11ea-993b-753fed2d89b0.jpeg)
![3063F340-FF10-4269-BDBD-1588653F11C2](https://user-images.githubusercontent.com/59847588/74565986-b9c84f80-4f72-11ea-8443-9b9dacd336d9.jpeg)

Could my drive be an issue? Because my laptop is listed as supported (see info above in this thread). I chose a partition volume of my internal HD and formatted APFS.

Any ideas?

**Comment by dosdude1** [comment]
It's probably a corrupt copy of the macOS installer. Use Catalina Patcher to download another copy, then try again.

**Comment by Noselip** [comment]
Thank you very much for the advice!
I now downloaded a fresh copy of the installer via Catalina Patcher and followed all the other steps, but unfortunately got the same screen after the installation reboot that "macOS could not be installed on your computer".

Anything else I could try?

Again, thx for programming this, it means a lot to be able to use older hardware vs. buying everything new just because Apple forces you to.

Best,
Noselip

**Comment by Noselip** [comment]
I also just tried it with the Mojave Patcher in both APFS and Mac OS Jornaled, same result..

**Comment by TonyVee73** [comment]
This happened to me on a 2010 MB Pro (6,2). I was using 16GB of RAM. This ram worked with High Sierra even though the laptop is to be use with a max of 8GB.

I put the original 4GB RAM and I got it up and running.

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps or just reading instructions: http://dosdude1.com/catalina/

Your comment has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
