### ISSUE TITLE
[SOLVED] pre-installed OSX Cata cant be moved.

### ISSUE THREAD

**Issue by juanpc2018** [dosdude1/macos-catalina-patcher#171]
in OSX,
its very easy to move the OSX HDD / SSD to another machine,
boot from USB3.0, Thunderbolt2/3, SATA, PCIe, etc...
gives freedom inside Apple Ecosystem,
Windows Not easy, Only USB2.0 chip,... MBR GPT Bios / Legacy, UEFI, OEM License, Activation, Anti-Cloning Security, WTG Enterprice, etc...
Linux also easy.

Anyway...
IF i install OSX Cata in a MacPro5,1 2010
i can`t move the HDD/SSD to another MacPro5,1 2010
gives forbiden boot logo.

OSX Cata is Node Locked,
to use the SSD in another non supported HW, 
i need to delete, format as APFS, and install again from OSX HSierra to the SSD or from USB, etc...

Not a Big Deal, but...
i tought Patch was Generic, Not serial number locked.

i tested changed/swap CPU trays, and still works, 
CPU Trays have a different Serial Nu,ber, 
patched OSX Cata is locked to MainBoard case Serial Number.

maybe moving OSX Cata could work in Supported Mac HW, like MacMini 2014, but havent tested.
Not able to move the HDD/SSD in unsupported HW could be a problem for some.

**Comment by joevt** [comment]
Catalina boot process requires APFS in firmware, or APFS in Driver#### boot variables, or APFS patch in EFI partition.

1)
Can you see APFS disks in the Startup Manager (hold Option key at boot)? For MacPro3,1 a APFS firmware patch exists.
https://forums.macrumors.com/threads/apfs-rom-patcher.2211396/
MacPro5,1 has firmware update that enables APFS boot support. Do you have the latest firmware?
https://forums.macrumors.com/threads/mp5-1-bootrom-thread-144-0-0-0-0.2132317/

2)
APFS in Driver#### just requires putting the apfs.efi EFI driver on a disk that is accessible during EFI boot. Use a nvram command to set a Driver#### variable that points to the apfs.efi EFI driver, and set the DriverOrder to include that Driver#### option.
https://gist.github.com/joevt/477fe842d16095c2bfd839e2ab4794ff

3)
Catalina Patcher has the ability to setup the last method (APFS patch in EFI partition). In the EFI partition, there should be:
- bootx64.efi : a renamed UEFI Shell.
- apfs.efi : the apfs EFI driver.
- startup.nsh : a UEFI Shell startup script that loads the apfs EFI driver, and boots Catalina by looking for `%targetUUID%\System\Library\CoreServices\boot.efi` which should be in the Preboot volume of the Catalina APFS container. `%targetUUID%` is the UUID of the Catalina volume.

Since MacPro5,1 supports APFS boot using method 1 (ignore method 2 and 3), you just need to make sure it has the firmware update.

Forbidden boot logo usually means macOS EFI boot loader (boot.efi) can't transfer from EFI disk access to macOS disk access.
Where was the disk connected in the first MacPro5,1?
Where is the disk connected on the second MacPro5,1?

Boot in verbose mode (add `-v` to boot-args. Take a picture when the forbidden boot logo appears.

Is SIP disabled?

**Comment by juanpc2018** [comment]
1. Yes, Both cMP 5,1 2010 have 144.0.0.0.0 FW
 required for NVMe boot.138 does Not work,
 also i have Kubuntu 20.10 in M.2 NVMe PCIe, works OK with 144.

2. i see All HDD / SDD / M.2 in Boot [Alt/Option]. 
with and without DarkBoot.
https://github.com/w0lfschild/app_updates/tree/master/DarkBoot
No problems,
using a flashed HD 7950 with MacEdition Rom.
has strange purple lines in Catalina boot screen, Not Big deal.
previously i had Nvidia GTX Titan 6GB, but sold it, 
Boot logo was Ok, No purple lines, but inside Catalina had weird size text in System Preferences, 
also had problems with some 32-Bit Software in older OSX HSierra, Mavericks.

3. Boot problem may be related to:
 http://www.sonnettech.com/product/tempossd.html

the SSD that had forbiden logo is connected to Sonnet Tempo PCIe
because MacPro 5,1 are SATA-II 3Gbps, but SSD are SATA-III 6Gbps.
boot time is increased considerably at 500MB/s.

i may test M2 PCIe in the future, much faster 16OOMB/s,
up to 25OOMB/s using the Sonnet 4x4 M.2 using all x16 PCIe lanes.

the other OSX Catalina i have in 2.5" HDD boots ok from SATA-II 3Gbps "Directly to Apple Board",
in the other machine,
can be moved...
but that OSX Cata does Not have installed the 3x Patch, has a windows that asks to install, but i have Not installed yet in that OSX.
could also be that.

the Sonnet 6Gbps PCIe,
im using the back SATA port, to avoid dust getting in the SATA connector by the PCI Fan.

**Comment by juanpc2018** [comment]
[EB|·P:MPI] N
[EB|·P:BPI] N
[EB|·'CS:CSKSD] {
[EB|·'CS:CSKSD] Err (0xE) @ GV 8D63D4FE-BD3C-4AAD-881D-86FD974BC1DF:boot-info-payload
[EB|#WL|6] 0x01 0x01    6  0x0E
[EB|·'CS:LFC]   {
[EB|·'LD:LF] FIO:  0,  DIR:  1,   P:  System\\Library\\Caches\\com.apple.corestorage\\EncryptedRoot.plist.wipekey,  DP:  0
[EB|·'FS:AGSVH]  Err (0xE)  @  LocHB  59D76AE4-37E3-55A7-B460-EF13D46E6020
[EB|·'G:CS] }  OK (0)
[EB|·'LD:LF] FIO:  0,  DIR:  1,  P:  <null string>,  DP:  1
[EB|·'B:SBS] SZ:  621112
[EB|#B:SHA]  f4031e1840ae80899574cd5a1feedc6b106d0f87
[EB|·'WL:PWLFNV]  Err (0xE)  @  GV wake-failure
[EB|·'WL:DT]  Err (0xE)  @  WL:PWLFNV
[EB|·'WL:PWLFRTC]  !  @  RTC:R
[EB|·'WL:DT] ERR (0xE)  @ WL:PWLFRTC  
[EB|·'FS:AGSVH]  Err (0xE)  @  ´AGU.0
[EB|·'FS:AGSVH]  !  @  ´END
[EB|#STOP|`B:OKRV]  !  @  FS:AGSVH
[EB|#WL|7]  0x01  0x03    6  0x0E
Exiting efiboot...
[EB|#WL|8]  0x01  0x03    6  0x0E

**Comment by juanpc2018** [comment]
i tested the other Catalina in the other identical machine, Boots OK with the Sonnet Tempo Dual SSD PCIe.

When installed in the same machine works Ok. SATAII & PCIe
when moved to other identical machine, PCIe FAIL, SATAII Works Ok

**Comment by juanpc2018** [comment]
Upgraded the FW of the Sonnet Tempo Dual Sata controlelr, 
will test if helps with this.

https://github.com/juanpc2018/Asmedia-AS2105-sata-to-USB-3

**Comment by juanpc2018** [comment]
Updating the firmware of the controller IC in the Sonnet Tempo Dual Sata PCIe solves the issue.
the FW in the Sonnet website has issues, too old, latest FW works ok.
but requires a Windows8.1 machine to update the FW.
i used another PC, Not bootcamp, unknown what could happen in Bootcamp.
Mac UEFI is delicated, can be Damaged by installing Windows1O directly.
SO = AT YOUR OWN RISK!.
