### ISSUE TITLE
Troubleshooting issues 

### ISSUE THREAD

**Issue by QuietAngel** [dosdude1/macos-catalina-patcher#27]
Please only file an issue here for code-related problems. This is not an issue system for resolving issues with using the compiled binaries.
- [ ] I understand
Since I’ve patched this OS my computers been completely upgraded but I’ve ran into a few issues that are detrimental. One, I can not boot my Mac in Safe Boot Mode, Recovery Mode and any other boot mode basically to troubleshoot a few issues such as the Safari extensions that are not enabled (purchased from the App Store etc..) I also turned on the “FileVault” very noob of me and got stuck with the encryption process and a greyed out “Turn Off FileVault” key. So I’m stuck in some tough spots now, does anyone “DosDude” included have any idea how to get past not being able to Reboot in these necessary Modes? Please help if you have the knowledge.

**Comment by iancbogue** [comment]
I asked the first part of your question over on r/CatalinaPatcher and got an answer I hadn’t thought about. Because Catalina can’t officially run on our Macs, it add a boot flag to disable checking the hardware (or is it software idk). Safe Mode disables boot flags, so it makes sense that you can’t boot into a Catalina safe mode with an older unsupported Mac. I’m not sure if there’s a way to get around this, which is unfortunate. That’s all I know.

**Comment by QuietAngel** [comment]
That makes total sense, but the biggest part of my issue is code related, as I’ve used terminal to try and disable FileVault and keep getting segmented fault errors. I have all of my information, passwords, etc.. If I can just get this FileVault to decrypt via terminal I’ll be the happiest Mac owner for sure at this point. Thanks for your help.

**Comment by LogoiLab** [comment]
This issue is covered by #29
