### ISSUE TITLE
Panic on sleep MacBookPro5,3

### ISSUE THREAD

**Issue by mark-turner** [dosdude1/macos-catalina-patcher#30]
Please only file an issue here for code-related problems. This is not an issue system for resolving issues with using the compiled binaries.
- [ x] I understand

I installed 10.15.4 yesterday using the latest patcher and the whole process went very smoothly. However, it hangs on sleep. The screen goes dark but fans keep running and the sleep LED lights up constantly (not blinking). Panic log attached.

[panic_log.txt](https://github.com/dosdude1/macos-catalina-patcher/files/4402091/panic_log.txt)

**Comment by mark-turner** [comment]
Should add that after the 180 second timeout, the panic message is displayed and then it reboots.

**Comment by SolidStill** [comment]
I've been experiencing the same on a MacBook Pro 5,2 - on fresh installs of Catalina, and currently on a fresh install of Mojave. 

I've tried: 

- changing many pmset settings (including setting hibernatemode to 0)

- resetting SMC with and without uninstalling the battery

- resetting NVRAM at same time as resetting SMC, and independently of resetting SMC

- installing optional patches, beyond those listed for my model, via Post Install utility on USB boot volume

- Enabling "Higher Performance" mode in Energy Saver preference pane, disabling the same

- Deleting /var/vm/sleepimage in case it's corrupted - before and after the other steps listed above

**Comment by mark-turner** [comment]
For me it does not matter whether on battery or AC.

**Comment by SolidStill** [comment]
I formatted by entire drive as APFS, not just the volume... what about you?

**Comment by mark-turner** [comment]
I formatted the disk as macOS extended, but the installer reformats it as APFS.

Behavior is no different on battery or not. 

Since the panic log indicates the crash was in IOGraphicsFamily, I thought I'd try switching to the other graphics card in this system (it has both an integrated GeForce 9400M and separate 9600 GT) but unfortunately it doesn't seem possible. No matter what I do, it displays the message "You must log out for this change to take effect" and when I log in again (even after restart) the setting has not changed and the 9400M is enabled even if the other is still selected in System Prefs. I'm guessing this is because the patch does not support the 9600GT.

**Comment by SolidStill** [comment]
Yeh... 5,2 has the exact same setup wrt to the graphics cards. Someone on the Discord server posited that the dual graphics setup may be the source of the issue; a number of people mentioning issues on dual gfx systems on Mac Rumours Forum too (threads about patched OS's on unsupported macs) but I did not discover any solution that stuck for me unfortuantely. Maybe you'll have bette luck seeing as your issue isn't identical to mine despite being extremely similar.

FWIW, there is a pmset setting called "gpuswitch" - mine was set to '2' after a clean install of macOS (I think a reinstall should return all the pmset values to defaults but I'm not certain by any means). I've tried changing this to "1" without success or indeed noticing any difference whatsoever - I haven't been able to find any documentation on "gpuswitch" thus far, so I'm simply guessing when I mess with these values.

**Comment by mark-turner** [comment]
I'm hoping at some point @dosdude1 will chime in on this. If it's not going to be fixed, at least it should be included in the known issues list, so that others can make an informed decision about whether to update. Honestly, a laptop that can't sleep is pretty much useless.

Thanks for the tip about gpuswitch. I'll try to play around with that tomorrow.

**Comment by dosdude1** [comment]
Use only the GeForce 9600M GT GPU, and sleep mode will work just fine. Set it to use High Performance Graphics using the Energy Saver pane of System Preferences.

**Comment by SolidStill** [comment]
Hi @dosdude1. Does that also apply when running off battery power in your experience? 

I just did another quick test by disconnecting my mag-safe cable and closing the lid - the front white LED went dark within ~20secs; I opened the lid and the unit was completely dead. Immediately after this, pressing the power button results in a brief flash of the white LED, without powering up the unit. The next power button press boots up, but shortly after the unit suddenly lost power while I was typing this message. 

I'm running on 'High Performance' and System Info does indeed show the display being run off the 9600.

This kind of behaviour only presents when running off battery power. I've tried installing a battery from another MacBook Pro 5,2 without any detectable difference - I should note that neither battery is new, but neither is in need of immediate replacement (according to the system or Coconut Battery).

Maybe worth mentioning:

1. I've been experiencing this behaviour despite fresh installs. I see on your video for the Catalina install that you're using a MacBook Pro 5,2 and, by sounds of it, clearly not having the issues others are having. What could possibly be different about my unit that could cause this behaviour? I've tried resetting the SMC/NVRAM numerous times - how can I be sure my settings are all "factory-defaults" beyond clean install + SMC/NVRAM resets? In particular, **are pmset settings returned to defaults by a clean install?**

2. I reformatted my entire disk as APFS rather than just a volume - might this have any bearing?

3. I am running Mojave but this issue was present with Catalina when testing 10.15.3

Thanks for your help!

**Comment by mark-turner** [comment]
Thanks for answering @dosdude1. It's working now! Yesterday I could not get System Prefs to accept the switch to the high performance setting (GeForce 9600 GT). It kept saying I had to log out, but after doing so (and even restarting) it was still stuck on the better battery life setting (9400M).

But today when I fired it up to check again, the high perf setting was enabled, and it sleeps fine. Go figure.

@SolidStill - I wish I could tell you how this happened, but it's a mystery. My only suggestion is to keep trying to change the setting, power off completely, and see if it stick on next boot.

**Comment by SolidStill** [comment]
@mark-turner Congrats... you lucky so and so :) I take it everythings working right when you're running off battery power too then?

**Comment by mark-turner** [comment]
@SolidStill so far everything seems to work except most third party apps crash with a code signing error. This also seems to be a widespread issue. System integrity protection is disabled, so I don't know why this is happening.

**Comment by mark-turner** [comment]
Whoops, just saw that dosdude1 came out with a new patcher that should fix this:
https://forums.macrumors.com/threads/macos-10-15-catalina-on-unsupported-macs.2183772/post-28325409
