### ISSUE TITLE
How to update to newe macOS?

### ISSUE THREAD

**Issue by masterhacka** [dosdude1/macos-catalina-patcher#33]
Hi guys,

I just wanted to know if there is any way to upgrade to macOS 10.15.4 (I am on 10.15.2) without creating a new installer and completely install the new version again. Thanks for your help!

**Comment by genfersee** [comment]
I have the same question!

**Comment by toshibochan** [comment]
I think but not sure. You will need make the usb installer just for reinstall the patch. If you update the OS without the usb patcher you not going to able to start the OS.

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps and reading instructions: http://dosdude1.com/catalina/

Your issue has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
