### ISSUE TITLE
Netflix, Zoom : video playback unavailable

### ISSUE THREAD

**Issue by flytodk** [dosdude1/macos-catalina-patcher#43]
Currently using Mac mini mid 2011 model (a1347, i5) and after updating using Catalina patcher, can't use Netflix (unable to play : keep saying there's some problem occurred) also, using zoom video meeting is not okay, since whenever using zoom, I can't see the others in screen. Looks like there's some graphic issues and don't know what it is. 

**update Netflix playback is okay with firefox, but still not available with chrome and safari.

**Comment by reven** [comment]
I have the same issue with zoom. My Mac is an MacBookPro8,1 (Early 2011). Everything else is flawless, except zoom video. I'll be glad to provide logs, configs or whatever you need to help troubleshoot. Or if you have any ideas what to check first I can try to figure it out.

**Comment by Reuben-G** [comment]
I have installed Zoom on two macbook pros mid 2009, one running 10.15.3 and one running 10.15.4.  Both have the same issue in as mach as the isight camera doesn't work and other participants images don't show.  The green light is on for the camera and it is allowed for Zoom in system preferences but doesn't work.  It works for Facetime, Skype and Photo Booth.

It feels like a permissions thing but I've no idea really.  Any ideas gratefully received.

**Comment by SolRosenberg** [comment]
MacBookPro7,1 Mid 2010 13" running 10.15.3 is also affected. Zoom doesn't show a video feed of me or participants in a meeting. FaceTime and PhotoBooth both work fine.

**Comment by andrehsiqueira** [comment]
Same problem here. 
MacBook Pro (13 polegadas, Early de 2011)
  Nome do Modelo:	MacBook Pro
  Identificador do Modelo:	MacBookPro8,1
  Nome do Processador:	Dual-Core Intel Core i7
  Velocidade do Processador:	2,7 GHz
  Número de Processadores:	1
  Número Total de Núcleos:	2
  Cache L2 (por Núcleo):	256 KB
  Cache L3:	4 MB
  Tecnologia Hyper-Threading:	Ativado
  Memória:	16 GB
  Versão da ROM de Inicialização:	87.0.0.0.0
  Versão do SMC (sistema):	1.68f99
  Número de Série (sistema):	C02FL537DH2H
  UUID do Hardware:	0AC4D5EC-059E-5267-B60C-2900913F7C66

  Modelo do Chipset:	Intel HD Graphics 3000
  Tipo:	GPU
  Barramento:	Integrado
  VRAM (Dinâmica, Máx.):	512 MB
  Fornecedor:	Intel
  ID do Dispositivo:	0x0126
  ID da Revisão:	0x0009

**Comment by patchupatch** [comment]
Same issue here. 
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro8,1
  Processor Name:	Dual-Core Intel Core i7
  Processor Speed:	2,8 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	MBP81.0050.B00  Chipset Model:	

Intel HD Graphics 3000
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	512 MB
  Vendor:	Intel
  Device ID:	0x0126
  Revision ID:	0x0009
  Displays:
Colour LCD:
  Display Type:	LCD
  Resolution:	1280 x 800
  UI Looks like:	1280 x 800
  Framebuffer Depth:	24-Bit Colour (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	No
  Connection Type:	Internal
 SMC Version (system):	1.68f99

**Comment by LvanProosdij** [comment]
This problem is known and nothing can be done as it is related to applications using Metal video acceleration on Catalina. Old computers/video card can't support Metal resulting in no video in some applications, of UI missing part like in Photos.

ZOOM : a workaround is to install an older version that do not use Metal for video playback. See : https://github.com/dosdude1/macos-catalina-patcher/issues/36

**Comment by jasonkim-jk** [comment]
There is a patch for non-Metal GPU from dosdude1.
See this link and patch the shell script.
I downloaded the lasted zoom version, it works after applying the patch.
 
https://forums.macrumors.com/threads/macos-10-15-catalina-on-unsupported-macs.2183772/page-428

**Comment by artkirienko** [comment]
## The Zoom application does not show any video during meetings
This is due to the latest Zoom versions requiring a Metal-compatible GPU for video rendering. To patch this out of the Zoom application, download and run the script located [here](http://dosdude1.com/catalina/zoomnonmetal.command.zip)

From FAQ here: http://dosdude1.com/catalina/

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps and reading instructions: http://dosdude1.com/catalina/

Your issue has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
