### ISSUE TITLE
Microsoft office Mac won't open

### ISSUE THREAD

**Issue by darrenmufc** [dosdude1/macos-catalina-patcher#51]
every time I try and open Microsoft office 2019 Mac it says Microsoft word quit unexpectedly MacBook model is mid 2009 with Catalina patcher

**Comment by joevt** [comment]
Every crash should have a crash log. Check Console.app?

**Comment by darrenmufc** [comment]
this is the error I get 
process:               Microsoft Word [5441]
Path:                  /Applications/Microsoft Word.app/Contents/MacOS/Microsoft Word
Identifier:            com.microsoft.Word
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Microsoft Word [5441]
User ID:               501

Date/Time:             2020-05-02 14:29:32.732 +0100
OS Version:            Mac OS X 10.15.4 (19E266)
Report Version:        12
Anonymous UUID:        D5EA3C3E-3535-4B27-AFC4-CD4547FC5349

Sleep/Wake UUID:       BC423119-0E8D-446E-990A-896911E2B4E2

Time Awake Since Boot: 2600 seconds
Time Since Wake:       1800 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010f23b000-0000000111300000 [ 32.8M] r-x/r-x SM=COW  

Thread 0 Crashed:
0   ???                           	0x0000000119355000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee09c4c50
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000119355000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x10f23b000 -        0x1112fffff +??? (0) <1D452792-51EF-31C1-8AFE-4F18878DE18C> (null)
       0x119354000 -        0x1193e5eff +??? (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1833
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=35.2M resident=0K(0%) swapped_out_or_unallocated=35.2M(100%)
Writable regions: Total=9076K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9076K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                            5152K        4 
__DATA_CONST                        20K        1 
__LINKEDIT                        2620K        3 
__TEXT                            33.3M        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                            105.0M       14

**Comment by stushep** [comment]
I'm getting the same error. Here's the crash log:

rocess:               Microsoft Word [2913]
Path:                  /Applications/Microsoft Word.app/Contents/MacOS/Microsoft Word
Identifier:            com.microsoft.Word
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Microsoft Word [2913]
User ID:               501

Date/Time:             2020-05-12 18:24:54.503 +0100
OS Version:            Mac OS X 10.15.4 (19E287)
Report Version:        12
Anonymous UUID:        1CEEB994-5CA4-DFE5-62E0-ABC64B94855E


Time Awake Since Boot: 40000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010b3ab000-000000010d470000 [ 32.8M] r-x/r-x SM=COW  

Thread 0 Crashed:
0   ???                           	0x0000000114d10000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee4854c50
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000114d10000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x10b3ab000 -        0x10d46ffff +??? (0) <1D452792-51EF-31C1-8AFE-4F18878DE18C> (null)
       0x114d0f000 -        0x114da0eff +??? (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 187676
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=35.2M resident=0K(0%) swapped_out_or_unallocated=35.2M(100%)
Writable regions: Total=9076K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9076K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                            5152K        4 
__DATA_CONST                        20K        1 
__LINKEDIT                        2620K        3 
__TEXT                            33.3M        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                            105.0M       14 

Model: iMac10,1, BootROM IM101.00D0.B00, 2 processors, Intel Core 2 Duo, 3.06 GHz, 12 GB, SMC 1.52f9
Graphics: kHW_NVidiaGeForce9400Item, NVIDIA GeForce 9400, 256 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x859B, 0x435434473353313036374D2E433136464B00
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x859B, 0x435434473353313036374D2E433136464B00
Memory Module: BANK 0/DIMM1, 2 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142353637334648302D4346382020
Memory Module: BANK 1/DIMM1, 2 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142353637334648302D4346382020
AirPort: spairport_wireless_card_type_airport_extreme (0x168C, 0x8F), Atheros 9280: 4.0.74.0-P2P
Bluetooth: Version 7.0.4f6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: Hitachi HDT721050SLA360, 500.11 GB
Serial ATA Device: PIONEER DVD-RW  DVRTS09
USB Device: USB 2.0 Bus
USB Device: Built-in iSight
USB Device: USB 2.0 Bus
USB Device: Internal Memory Card Reader
USB Device: USB2.0 Hub
USB Device: Live! Cam inPerson HD VF0720
USB Device: Live! Cam inPerson HD VF0720
USB Device: USB Bus
USB Device: IR Receiver
USB Device: Wireless Receiver
USB Device: USB Bus
USB Device: Yeti Stereo Microphone
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus:

**Comment by stushep** [comment]
I must add that Microsoft Teams and Outlook run fine. However, Word, PowerPoint and Excel all fail

**Comment by santiruiz** [comment]
Hi, I have the same problem and I solve it with the following steps:

1. Open the Finder.
2. Go to Applications.
3. Find the Office application that cannot be opened, (word, excel, etc.)
4. Press the ctrl key and holding it down, click on the application. This action open a context menu.
5. Press open.

Once these steps are followed, the rest of the times can open the application normally without having to repeat them.

**Comment by gyodsl** [comment]
> Hi, I had the same problem and I’ve solved it following these steps:
> 
> 1. Open the Finder.
> 2. Go to Applications.
> 3. Find the Office application that cannot be opened, (word, excel, etc.)
> 4. Press the ctrl key and holding it down, click on the application. This action open a context menu.
> 5. Press open.
> 
> These steps must be followed only once. From that moment onwards, the application can be used normally without having to repeat them anymore.

I tried and sometimes it opens and sometimes it doesn't. but it is too unstable. I tried it with office 2019. with 2016 the same thing happens?

**Comment by ralphm3141** [comment]
Please help! I am having the exact same problem. All native Catalina apps open just fine, but third party apps, particularly Office, don't open most of the time. Every once in a while when Catalina is in a good  mood it works, but most of the time I just get the error "quit unexpectedly".

I am using a MBP 6,2.

I was using Catalina just fine on this same machine, which I upgraded from High Sierra, but over the weekend I decided to do a clean install of Catalina. Its been a nightmare. I clean installed twice. I've reset cache. I've reinstalled patches. I've tried installing apps using web downloads and using installer, and I've tried installing apps using terminal (brew/cask/mas). NOTHING makes a difference. 3rd party apps just won't launch, which Office being the worst. Please Help! I've committed to Catalina and I can't go back to High Sierra.

**Comment by ralphm3141** [comment]
> Please help! I am having the exact same problem. All native Catalina apps open just fine, but third party apps, particularly Office, don't open most of the time. Every once in a while when Catalina is in a good mood it works, but most of the time I just get the error "quit unexpectedly".
> 
> I am using a MBP 6,2.
> 
> I was using Catalina just fine on this same machine, which I upgraded from High Sierra, but over the weekend I decided to do a clean install of Catalina. Its been a nightmare. I clean installed twice. I've reset cache. I've reinstalled patches. I've tried installing apps using web downloads and using installer, and I've tried installing apps using terminal (brew/cask/mas). NOTHING makes a difference. 3rd party apps just won't launch, with Office being the worst. Please Help! I've committed to Catalina and I can't go back to High Sierra.

Also worth noting, when I first do the install, and relaunch Catalina patcher to post-install patches, it re-installs patches just fine. If I then go on and build out the clean installed OSX and start updating/installing apps, and then try re-install patches, Patcher says I no longer have a valid copy of Catalina.

**Comment by apkalexei** [comment]
Try with this command: sudo nvram boot-args=amfi_get_out_of_my_way=0x1

**Comment by rodolphoramirez** [comment]
Hi guys. I had this problem too. First I've downloaded Office installer from MS website. After running installation I've run into this crashing screen when initiating Word, Power Point and Excel.
I solved it by uninstalling Office and re-installing it from Mac's AppStore! Running fine right now!
I hope it helps you guys :)

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps or just reading instructions: http://dosdude1.com/catalina/

Your comment has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.

**Comment by chriswayg** [comment]
Third-party applications do not open or crash on launch

> To work around this, immediately relaunch the affected application after receiving the crash message. After that point, the affected application should no longer experience this crash.

This does not really work, as it can take about a dozen attempts before an app will finally start without crashing. There must be a better solution than this unsatisfactory workaround.

Version: 10.5.7 
- 1Password
- coconutBattery

**Comment by back2msg** [comment]
1. Open a new Terminal app window
2. Type in the following:
     sudo xattr -dr com.apple.quarantine /Applications/Microsoft\ Word.app
     sudo xattr -dr com.apple.quarantine /Applications/Microsoft\ Excel.app
     sudo xattr -dr com.apple.quarantine /Applications/Microsoft\ Powerpoint.app
     sudo xattr -dr com.apple.quarantine /Applications/Microsoft\ Outlook.app
     sudo xattr -dr com.apple.quarantine /Applications/Microsoft\ Note.app
3. Press enter
4. Enter password
5. Close Terminal
6. Restart
7. Try opening the app again

These commands worked for me 
Give a try for yourselves.

**Comment by chriswayg** [comment]
@dosdude1, **_would it be possible to port the fixes that apparently resolve this issue in the Big Sur OpenCore Legacy Patcher to the Catalina Patcher?_** 

None of the workarounds for the code signing bug are a sufficient solution. I have multiple applications exhibiting this bug with the crash `EXC_CRASH (Code Signature Invalid)`, among them 1Password and coconutBattery. 

1) Sometimes its enough to try starting the app multiple times

2) Sometimes it works after starting the app from the terminal with `/Applications/1Password 7.app/Contents/MacOS/1Password 7` for example

3) Sometimes the above fixes do not persist

4) The manual signing of the app seems to work in this case:

```
sudo xattr -lr /Applications/coconutBattery.app
sudo xattr -lr /Applications/coconutBattery.app
sudo codesign -f -s - /Applications/coconutBattery.app
```

5) Disabling almost all basic security is just not acceptable:
`sudo nvram boot-args=amfi_get_out_of_my_way=0x1,`

Altogether this is a very unsatisfactory situation as the behavior is totally unpredictable, and especially since there are no such issues in Big Sur using OpenCore Legacy Patcher. But I cannot run Big Sur on my MacBook Pro 2010 due to graphics issues which do not occur in Catalina. 

The Catalina Patcher has not received any updates for about 2 years and has not been updated for 10.15.7 (Build 19H15) it seems, but the OpenCore Legacy Patcher is not supported for Catalina.

### Applications which crash repeatedly

-  Adobe Desktop Service 
- 1 Password 7 (manually signing breaks the app)
- coconutBattery
- OmniDiskSweeper
- Opera GX (repeatedly fails to start, but no crash in logs)
- BBEdit

### System Info for MacBook Pro 2010
```
OS                             macOS Catalina Version 10.15.7 (Build 19H15)
RAM                            8.00 GB
Model Identifier               MacBookPro6,2
CPU                            Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
GPU Name                       GT216M [GeForce GT 330M]
Catalina Patcher               version 1.4.4
```

**Comment by mlseguin** [comment]
nothing worked for me except fixing permision : [https://appletoolbox.com/fix-corrupt-user-accounts-macos/](https://appletoolbox.com/fix-corrupt-user-accounts-macos/)
