### ISSUE TITLE
Camera (iSight) permissions

### ISSUE THREAD

**Issue by sopousa** [dosdude1/macos-catalina-patcher#52]
Hello

I installed the patch in a Macbook Air 4,2 and I try to use Zoom or Skype and the camera don't works. The problem is that not appear the app in the privacy section to give the permission to access to camera. However, with Photo Booth it works perfectly...

Someone has the same problem?

Thanks

**Comment by LvanProosdij** [comment]
This problem is known and nothing can be done as it is related to applications using Metal video acceleration on Catalina. Old computers/video card can't support Metal resulting in no video in some applications, of UI missing part like in Photos.

ZOOM : a workaround is to install an older version that do not use Metal for video playback. See : https://github.com/dosdude1/macos-catalina-patcher/issues/36

**Comment by sopousa** [comment]
Hi

Thanks for the reply. I reinstalled Catalina with the last version of patch and I installed older version of ZOOM for not use Metal and it works.

Thank you very much
