### ISSUE TITLE
Google Chrome won't open

### ISSUE THREAD

**Issue by TonyVee73** [dosdude1/macos-catalina-patcher#53]
I recently used the Catalina Patcher on my 2010 MB Pro 6,2. Google Chrome was working fine.

Then I created a new volume and installed High Sierra so I can use non compatible programs. When I switched back to Catalina, Chrome won't open.

Any assistance will be greatly appreciated!!!!

Process:               Google Chrome [3377]
Path:                  /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Identifier:            com.google.Chrome
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Google Chrome [3377]
User ID:               501

Date/Time:             2020-05-04 09:22:07.619 -0400
OS Version:            Mac OS X 10.15.4 (19E287)
Report Version:        12
Anonymous UUID:        48730AF2-60D5-809F-580A-8AFCCBDAD152

Sleep/Wake UUID:       A33FB07E-16F6-435A-B4CA-7279DC2CB282

Time Awake Since Boot: 6800 seconds
Time Since Wake:       2300 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010b078000-000000010b0a2000 [  168K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   @ܕ                           	0x0000000114187000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee4b87be8
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000114187000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x10b078000 -        0x10b0a1ff7 +@ܕ (0) <07DECCFB-8719-3F56-9927-843F52800CD5> @ܕ
       0x114186000 -        0x114217eff +@ܕ (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> @ܕ

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 3379
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1004K resident=0K(0%) swapped_out_or_unallocated=1004K(100%)
Writable regions: Total=8408K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8408K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             232K        4 
__DATA_CONST                        20K        1 
__LINKEDIT                         252K        2 
__TEXT                             752K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             65.2M       13 

Model: MacBookPro6,2, BootROM 99.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 2.4 GHz, 4 GB, SMC 1.58f17
Graphics: kHW_IntelGMAHDItem, Intel HD Graphics, spdisplays_builtin
Graphics: kHW_NVidiaGeForceGT216Item, NVIDIA GeForce GT 330M, spdisplays_pcie_device, 256 MB
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142353637334648302D4346382020
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1067 MHz, 0x80CE, 0x4D34373142353637334648302D4346382020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.106.98.102.31)
Bluetooth: Version 7.0.4f6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: SanDisk SDSSDH3 1T00, 1 TB
Serial ATA Device: MATSHITADVD-R   UJ-898
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Wireless Device
USB Device: IR Receiver
USB Device: Built-in iSight
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Internal Memory Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus:

**Comment by MrNeedSomeHelp** [comment]
I also have the same problem

Process:               Google Chrome [600]
Path:                  /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Identifier:            com.google.Chrome
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Google Chrome [600]
User ID:               501

Date/Time:             2020-05-17 08:59:06.055 +0100
OS Version:            Mac OS X 10.15.4 (19E287)
Report Version:        12
Anonymous UUID:        9E742789-6353-4D64-91FE-023B587DF055


Time Awake Since Boot: 670 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010dcea000-000000010dd14000 [  168K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   ???                           	0x0000000111e1d000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee1f15bf0
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000111e1d000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x10dcea000 -        0x10dd13ff7 +??? (0) <88883176-C47D-3B50-BF83-B4736D0E320D> (null)
       0x111e1c000 -        0x111eadeff +??? (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 416
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1004K resident=0K(0%) swapped_out_or_unallocated=1004K(100%)
Writable regions: Total=8408K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8408K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             232K        4 
__DATA_CONST                        20K        1 
__LINKEDIT                         252K        2 
__TEXT                             752K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             65.2M       13 

Model: MacBookPro5,5, BootROM MBP55.00AC.B03, 2 processors, Intel Core 2 Duo, 2.53 GHz, 4 GB, SMC 1.47f2
Graphics: kHW_NVidiaGeForce9400MItem, NVIDIA GeForce 9400M, 256 MB
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1067 MHz, 0x802C, 0x31364A53463235363634485A2D3147314631
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1067 MHz, 0x802C, 0x31364A53463235363634485A2D3147314631
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8D), Broadcom BCM43xx 1.0 (5.106.98.102.31)
Bluetooth: Version 7.0.4f6, 3 services, 25 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: SanDisk SSD PLUS 120 GB, 120.04 GB
Serial ATA Device: HL-DT-ST DVDRW  GS23N
USB Device: USB 2.0 Bus
USB Device: Internal Memory Card Reader
USB Device: USB 2.0 Bus
USB Device: Built-in iSight
USB Device: USB Bus
USB Device: MULTI-DIRECTION OPTICAL MOUSE
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
Thunderbolt Bus:

**Comment by TonyVee73** [comment]
> I also have the same problem

I found a fix on a Mac Rumors Cat Patcher forum. Its' post #10,033
https://forums.macrumors.com/threads/macos-10-15-catalina-on-unsupported-macs.2183772/page-402?post=28354240#post-28354240
