### ISSUE TITLE
Installation stuck on late 2011 Mac Mini

### ISSUE THREAD

**Issue by ydotmalik** [dosdude1/macos-catalina-patcher#67]
The installation is stuck on my late 2011 Mac Mini during the full installation process, when the background is black and all you see is the Apple logo and progress bar. I've been waiting for almost 10 hours now, and the installation is still about 40% complete. The screen originally said 'Estimated time remaining' for a long time. When I pressed the power button, the screen said 'Your Mac will restart when the update completes.' However, it's been like this overnight.

I followed the [official Catalina installer video](https://www.youtube.com/watch?v=wxFzZWqoCng) and the installation is stuck [at this step](https://youtu.be/wxFzZWqoCng?t=1019). When I rebooted the machine, the installation seemed to pick up where it left off, but it still gets stuck.

I originally had High Sierra installed.

**Comment by traveler130** [comment]
Same issue here. Late 2008 Macbook running Mavericks.

**Comment by freiand** [comment]
Same here on a Mac Mini 4,1 (2010) running latest High Sierra.

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps and reading instructions: http://dosdude1.com/catalina/

Your issue has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
