### ISSUE TITLE
"The volume 'Catalina' does not appear to have a valid copy of macOS Catalina" at post install patches. 

### ISSUE THREAD

**Issue by wedouree** [dosdude1/macos-catalina-patcher#68]
Hi, 
 I have an iMac 2008 8,1. 
I get this notice when I try to apply patches at 'Post Install Patches'. Then it proceeds to apply but then an 'Error' message pops up and then after 10 seconds, reboots the system back to the macOS Utilities page. I followed dosdude1's amazing tutorial and everything did what it was meant to do up until this part. 
I'm not too sure where to go from here. 

The volume I named Catalina is in APFS and the external drive has used only 10.49GB (for the patcher) out of 30.77GB. These are the only two drives that pop up on the side bar in Disk Utilities. I wanted to update this iMac for my parents but no idea where to go from here. If I were to restart I'm not too sure how to do that either someone help :((

**Comment by itsthejb** [comment]
Just installing myself and encountered the same problem. I believe this is simply because the install doesn't complete until you restart the machine; then install finishing from the drive. After this Catalina should be installed (it's completing for me right now). _After that_ boot back into the installer and run the post install

I'm also installing to APFS on a home-made Fusion Drive, and it appears to be working

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps or just reading instructions: http://dosdude1.com/catalina/

Your comment has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.

**Comment by lewisdonofrio** [comment]
> 
> 
> Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps or just reading instructions: http://dosdude1.com/catalina/
> 
> Your comment has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.

What "common steps" I'm getting this ("The volume 'Untitled' does not appear to have a valid copy of macOS Catalina") as well on my iMac8,1 and then I get 
![20201217_231238](https://user-images.githubusercontent.com/3161117/102573972-acfa1800-40bd-11eb-98bf-7c51f065f616.jpg)
