### ISSUE TITLE
Final Cut pro Gpu (error) 

### ISSUE THREAD

**Issue by Clif90** [dosdude1/macos-catalina-patcher#72]
MacBook Pro Late 2011
Whit Catalina 10.15.5
Final Cut dont show image... GPU error... Legacy Video Card Patch are installed

**Comment by Clif90** [comment]
![15925649107891198243934883660690](https://user-images.githubusercontent.com/67149240/85126569-088e3a80-b22e-11ea-85c2-dc79530493d8.jpg)
![15925649412785618157562614711446](https://user-images.githubusercontent.com/67149240/85126609-1fcd2800-b22e-11ea-94fa-7a83291ce6e3.jpg)

**Comment by weslima1978** [comment]
Hello friend!
I have the same problem... Did you get any solution? Thank you! 
MacBook Pro late 2011 whit Catalina 10.15.5 (Patcher)

**Comment by Clif90** [comment]
No 🙄 it still not working

**Comment by weslima1978** [comment]
The solution for me was to install version 10.4.6... this worked Viewer.

**Comment by LogoiLab** [comment]
This is a metal rendering related issue.

Your issue has been closed because it is a common problem that can be understood by reading instructions: http://dosdude1.com/catalina/

Your issue has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
