### ISSUE TITLE
Problem with Virtualization like VMWare

### ISSUE THREAD

**Issue by nimaam** [dosdude1/macos-catalina-patcher#73]
I have a problem with Vmware and now with android studio virtual phone all these software tell your CPU doesn't support virtualization.

**Comment by nimaam** [comment]
no one has a clue for this problem?????? I can not do any virtualization here in my mac pro late 2008

**Comment by jaymagik** [comment]
I would suggest Clover EFI and Clover Configurator. I can't promise that it will work, but it is specifically made to patch older hardware so that it works with current software.

**Comment by YeaToast** [comment]
That's right. You have to download an older version of VMware Fusion and/or Android Studio to be able to support virtualization. I, from my personal experience have tried virtualizing with VMware fusion 11, but had the same error. I switched back to Fusion 8, and everything works fine. It's the CPU type that doesn't support that kind of virtualization, as it's deprecated.

**Comment by joevt** [comment]
I use Parallels. It has a major slow down (related to disk access?) on my MacPro3,1 (2008) since Mojave 10.14.4 when using a Windows 7 VM (same problem in a Windows 10 VM). Mojave 10.14.3 has no problem. It still works in Catalina 10.15.6 but for Windows I use Parallels on my Macmini8,1 (2018). I can use Parallels on my MacPro3,1 for EFI testing - maybe Linux?

I don't think there's anything the patcher can do or this problem is beyond the scope of what the patcher is supposed to do.

Clover should probably not be used on a real Mac Pro (NVRAM corruption?)

**Comment by LogoiLab** [comment]
@nimaam Your system does not have the proper microcode to support virtualization depending on what CPU you have. This is a limit of old hardware, not of Catalina Patcher.

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem for older hardware and cannot be fixed by any software whatsoever.

Your issue has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
