### ISSUE TITLE
Installation Never Starts

### ISSUE THREAD

**Issue by lcharlesgoddard** [dosdude1/macos-catalina-patcher#77]
Repeated attempts to load Cataline Patcher stall with SUCCESS, but the installation never starts on 2009 iMac

**Comment by xceot** [comment]
I have same problem on a 2008 Mac Pro 3,1 :) After the booter works flawless.....reboots tries to install Catalina reboots back into bootable drive.

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps and reading instructions: http://dosdude1.com/catalina/

Your issue has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
