### ISSUE TITLE
Not installing on Mac Pro 5,1

### ISSUE THREAD

**Issue by humstrum** [dosdude1/macos-catalina-patcher#78]
Please only file an issue here for code-related problems. This is not an issue system for resolving issues with using the compiled binaries, or discussing functionality issues with Catalina on your unsupported machine.
- [x] I understand
Mac Pro 5,1 previously running dosdude1 high Sierra. Followed instructions on dosdude1 YouTube channel. Tried patcher on USB stick and also a USB external hard drive. Destination internal drive had an APFS volume added and erased. Initial 7 minute section of install works, then the Apple logo on white screen and black progress bar.....but this I s very slow and stops after only a small amount of progress. Then screen changes to grey progress bar and returns to disk utility. If I start the computer and hold down option key, only the efi /usb boot option is visible.....no other drives. How can I solve this?

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps and reading instructions: http://dosdude1.com/catalina/

Your issue has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.
