### ISSUE TITLE
Couldn't  Unmount Error on creating USB Stick

### ISSUE THREAD

**Issue by clipse2004** [dosdude1/macos-catalina-patcher#8]
Hello, 

i have a problem, I will create a bootable usb stick, so after downloading Catalina I click on USB Stick and after a few minutes I got this error:
Mounting BaseSystem.dmg...
"/dev/disk5          	GUID_partition_scheme          	
/dev/disk5s1        	Apple_HFS                      	/private/tmp/basesystem
Patching BaseSystem.dmg...
hdiutil: couldn't unmount "disk5" - Ressource ist belegt"

can you help me? I tried it on a Mac mini late 2014 and a old Mac mini. 

Big thanks

**Comment by kapln74** [comment]
Any updates?
I have the same issue on a iMac 21.5 Mid 2010 macOS High Sierra!

**Comment by clipse2004** [comment]
No but don’t quit installation, just click on retry and then it works

**Comment by kapln74** [comment]
Hi clipse2004. No, it's not :-(

**Comment by beanstalker** [comment]
I have a similar problem. Tried installing on a variety of USB drive and hard disks, all to no avail. The system I'm patching on is running Catalina (I'm doing the download and patching on a newer Mac, and I intend to use it to install Catalina on my older Mac). I thought perhaps Catalina was the issue so I tried using my partners Mac which is running Mojave. Same problem persists.

The error message I get:

> **Error Saving BaseSystem Image**
> An error occurred while attempting to save the BaseSystem image. Ensure that there is at least 10GB of free space on your Startup Disk, then try again.

And when I click View Log:

> Mounting BaseSystem.dmg...
> 
> /dev/disk4          	GUID_partition_scheme          	
> /dev/disk4s1        	Apple_HFS                      	/private/tmp/basesystem
> 
> 
> Patching BaseSystem.dmg...
> 
> hdiutil: couldn't unmount "disk4" - Resource busy

I definitely have more than enough space only startup disk, so the error message is incorrect.

I tried re-running the installation as suggested above, but this didn't work on my Catalina Mac. On the Mojave Mac the installation then progressed almost to the end, but then the same error and log messages came up, except the image it couldn't unmount this time was InstallESD.dmg instead of BaseSystem.dmg.

Any suggestions would be much appreciated.

Many thanks,
Jack

**Comment by LvanProosdij** [comment]
Are you trying to create the bootable USB stick on a T1 or T2 equipped Mac ?

I had the problem on a 2019 MacBook Pro (under Catalina), exact same problem as yours. I had to to use an older MacBook Air (under Mojave) to successfully create an USB stick.

**Comment by beanstalker** [comment]
Thanks for the reply LvanProosdij,

Sounds interesting; please excuse my ignorance but what do you mean by "T1 or T2 equipped Mac". Is that the new security chip?
I don't think mine has one, it's a mid 2014 MacBook Pro 11,3 : I think that's before they added the security chips. Where do I find the T1/T2 in system profiler (Is it "Controller"? there's nothing listed there)?

**Comment by beanstalker** [comment]
I also tried using a Mojave virtual machine hosted on Catalina/VMware. That worked to create a patched .iso image (creating the .iso image on my Catalina host had the same problem as above), but not a bootable USB (It can't access the USB passed through from the host properly).

Trying to work out if I can create a bootable USB from the patched .iso (No optical drive in the old Mac that I want to update...).

**Comment by LvanProosdij** [comment]
Yes thats the new security chips. Can't tell from my own experience if the problem is related to the T2 chip or to Catalina, but had to use an older Mojave based Mac to succeed creating the bootable USB stick. 

Note that on the Catalina Mac I unsuccessfully tried to solve the problem by copying the Patcher un Applications' folder and giving it "full disk access" in security panel. Also gave Terminal App full access.

**Comment by nimaam** [comment]
I have Mac Pro 4,1 late 2008 and want to install catalina but in all way even I make Iso or USB the patcher give me an error on mount base system, could you please help me on it?

**Comment by shoaib03339770257** [comment]
yes me too faced with this issue 
any one have a confirmed solution ?

**Comment by clipse2004** [comment]
I'll do it if I can set a clearance for the patcher in Little Snitch.
Sometimes I have to try two to three times until it works.

**Comment by LogoiLab** [comment]
Your issue has been closed because it is a common problem that can be remedied by taking the appropriate steps or just reading instructions: http://dosdude1.com/catalina/

Your comment has also been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for code-related problems only.

**Comment by softmimi** [comment]
> Hello,
> 
> i have a problem, I will create a bootable usb stick, so after downloading Catalina I click on USB Stick and after a few minutes I got this error:
> Mounting BaseSystem.dmg...
> "/dev/disk5 GUID_partition_scheme
> /dev/disk5s1 Apple_HFS /private/tmp/basesystem
> Patching BaseSystem.dmg...
> hdiutil: couldn't unmount "disk5" - Ressource ist belegt"
> 
> can you help me? I tried it on a Mac mini late 2014 and a old Mac mini.
> 
> Big thanks

Hi
 I had same issue with my 2008 Imac and i fix it 
 This issue happens when you already have a copy of 
 Catalina and try to use Catalina patcher . 
 You need to download Catalina from Catalina patcher 
 And it'll work just fine .
![16021185584271754807278461282645](https://user-images.githubusercontent.com/72532397/95403188-4211bf80-095d-11eb-9a9f-5a660a754f94.jpg)
