### ISSUE TITLE
ExpressCard/34 doesn't work even after official driver reinstalled

### ISSUE THREAD

**Issue by vitalz** [dosdude1/macos-catalina-patcher#90]
Tempo Duo ExpressCard/34 doesn't work on Catalina even after official driver "forcefully" reinstalled: i.e., though an icon displays in system tray mac does never see any disks/devices attached.

![ExpressCard](https://user-images.githubusercontent.com/2794044/91188511-0d71dd80-e6fa-11ea-973e-98680d43eb8c.png)

**Comment by joevt** [comment]
This problem seems out of scope for Catalina patcher.

What does "official driver" mean? Where is it from? The manual says macOS comes with all the needed drivers.

Is the ExpressCard/34 connected before boot?

What kind of disks/devices have you tried?

Are the disks/devices connected before boot?

Can you connect a mouse or keyboard to a USB port of the ExpressCard/34?

Have you tried connecting the USB 2.0 micro B connector of the Tempo Duo to a USB port? This is required for bus powered USB drives.

The ExpressCard/34 can be connected to a modern Mac using the Sonnet Echo ExpressCard Pro. I wonder if the behaviour is different with that? There's an "SxS driver 3.0" for the Sonnet Echo ExpressCard Pro in Catalina. I don't know if that has anything to do with PCIe-Based ExpressCard/34 devices like the Tempo Duo. In the Compatible Products tab, it says the Tempo Duo in the ExpressCard Pro requires that the Tempo Duo have extra power from a USB 2.0 connection.

**Comment by LogoiLab** [comment]
Your comment has been closed because it counts as off-topic according to the community guidelines which state that GitHub issues are for patcher code-related problems only.

**Comment by vitalz** [comment]
@joevt Yes, tech spec says macOS already has this driver. But some people posted there is no driver since Catalina (10.15).
That is why in just experimental interest I downloaded from [official page](http://www.sonnettech.com/support/kb/kb.php?cat=339&expand=_a3&action=b146#b146) and installed it again.

> Have you tried connecting the USB 2.0 micro B connector of the Tempo Duo to a USB port?

Per a screenshot attached it is obvious mini-USB power was connected into Macbook USB2.0 port which was used as power supply: otherwise it will never show indicator in system tray (or ExpressCard status in System Report) when this card does not use microUSB as power supply.

But appreciate you comment on **ExpressCard/34 should be connected before boot**: it would work in that case. When _Sonnet Tempo Duo ExpressCard/34_ is connected before boot then lower USB3.0 port will be able to mount external disks and USB mouse will connect successfully both ports and work but upper USB3.0 port still won't see external disks. 

![lower usb in expresscard](https://user-images.githubusercontent.com/2794044/91283206-f501d180-e792-11ea-9b50-172608624575.png)

**Comment by joevt** [comment]
Are you sure that driver has anything to do with the SATA controller used by the Tempo Duo? It might use a different controller than the other Sonnet SATA devices.

If you have no eSATA devices then there's no point installing a SATA driver.

You say both USB ports work for a USB 2.0 mouse, but not for a USB 3.0 disk. Is the USB disk bus powered or not?
When the mouse is connected to the upper port, does the Current Available and Required numbers appear the same as for the bottom port?
